name: "Clone Target"
description: "Clones the target repository for testing"
inputs:
  target_id:
    required: true
  pat_token:
    required: true
  repo:
    required: true
runs:
  using: "composite"
  steps:
    - name: Clone
      shell: bash
      run: |
        set -euo pipefail

        GH_TOKEN=${{ inputs.pat_token }} gh repo clone "${{ inputs.repo }}" "apps/${{ inputs.target_id }}"
