name: QA - AI Text Summarizer App Frontend
on:
  repository_dispatch:
    types: [run-ai-text-summarizer-app-frontend-tests]

jobs:
  call-template:
    uses: ./.github/workflows/qa-base.yaml
    with:
      project_id: "ai-text-summarizer-app-frontend"
    secrets: inherit
