name: Base Template
on:
  workflow_call:
    inputs:
      project_id:
        required: true
        type: string

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Debug dispatch
        run: echo '${{ toJson(github.event) }}'

      - name: Setup Hub
        uses: ./.github/actions/setup-hub
        with:
          workspace_name: ${{ github.event.client_payload.workspace_name }}

      - name: Clone Target
        uses: ./.github/actions/clone-target
        with:
          repo: ${{ github.event.client_payload.repo }}
          target_id: ${{ inputs.project_id }}
          pat_token: ${{ secrets.QA_HUB_PAT }}

      - name: Prepare App
        uses: ./.github/actions/prepare-app
        with:
          target_id: ${{ inputs.project_id }}

      - name: Run Tests
        uses: ./.github/actions/test-runner
        with:
          workspace_name: ${{ github.event.client_payload.workspace_name }}
