name: QA - Rick and Morty Graphs and Stuff
on:
  repository_dispatch:
    types: [run-rick-and-morty-graphs-and-stuff-frontend-tests]

jobs:
  call-template:
    uses: ./.github/workflows/qa-base.yaml
    with:
      project_id: "rick-and-morty-graphs-and-stuff-frontend"
      # The workspace name is the name of the package in the monorepo
      workspace_name: "@hub/rick-and-morty-graphs-and-stuff-frontend"
    secrets: inherit
